name: "Angular Deploy gh-pages Actions"
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: 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
          build_configuration: production
          base_href: https://julianocanuto.github.io/gerenciador-de-tarefas/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/gerenciador-de-tarefas
